### ISSUE TITLE
权限 getButtonList bug  

### ISSUE THREAD

**Issue by micropu** [anjoy8/Blog.Admin#12]
bug提交，项目：Blog.Core admin ,代码位置  getButtonList，原因：原代码定义buttonList为公共变量，造成某一页面获取 ButtonList后，其它页面就算刷新失败或不刷新，也会有其它页面的buttonList,
修改结果：  把buttonList 修改变私有变量即可：

修改后代码如下：
![QQ图片20200717110332](https://user-images.githubusercontent.com/54704152/87744120-38c0fd00-c81d-11ea-9972-b3774a94459e.png)

**Comment by anjoy8** [comment]
good
