### ISSUE TITLE
建议增加灵活权限控制示例

### ISSUE THREAD

**Issue by micropu** [anjoy8/Blog.Admin#13]
原<toolbar :buttonList="buttonList" @callFunction="callFunction"></toolbar>不太灵活，动态绑定函数
无法解决一些传参问题，建议增加以下示例，有V-if 单项控制button是否显示方式
<el-button  v-if="CheckAuthorize('编辑')"  size="small" @click="handleEdit(scope.$index, scope.row)">编辑</el-button>

//查找是否有权限，没有返回undefined
    CheckAuthorize(name){
      var result = false
      this.buttonList.find((item)=>{
        if(item.name===name){
          result = true
          return
        }
      })
      return result
    },

**Comment by anjoy8** [comment]
good
