### ISSUE TITLE
菜单默认都被点击

### ISSUE THREAD

**Issue by o-skyworth** [anjoy8/Blog.Admin#2]
比如登录test1用户，其它用户登录都是一样，登录成功后QQ欢迎页，用户角色管理，菜单权限管理，报表管理都默认被点击了，猜测应该是src/router/index.js文件里面的createRouter数组内容少了

**Comment by anjoy8** [comment]
没发现你这个问题，一切请以线上为主，如果是你本地代码问题，请自行调试

**Comment by o-skyworth** [comment]
不科学啊，都是刚刚clone的代码啊
