### ISSUE TITLE
npm run build前后，如何配置接口Api地址

### ISSUE THREAD

**Issue by CatcherX** [anjoy8/Blog.Admin#26]
https://github.com/anjoy8/Blog.Admin/blob/25ee2cd9f3ad400c438541a41b07b4d3e5bc9b58/vue.config.js#L43

本地开发环境，执行 npm run serve ，可以调用到9291的接口地址。
执行npm run build，部署到服务器，点击登录，请求的接口地址变成了当前域名的。
请教如何指定域名呢？（接口项目可通过nginx处理跨域请求）

**Comment by anjoy8** [comment]
用nginx配置反向代理，参考我的nginx
http://apk.neters.club/.doc/guide/function-sheet.html#四、nginx一览表
