### ISSUE TITLE
点击博客管理按钮报错“服务器错误”

### ISSUE THREAD

**Issue by o-skyworth** [anjoy8/Blog.Admin#4]
点击博客管理按钮报错“服务器错误”，原因是wwwRoot下的Blog.Core.Table&Data.sql语句中的BlogArticle表中缺少IsDeleted字段和值

**Comment by anjoy8** [comment]
没发现你这个问题，一切请以线上为主，如果是你本地代码问题，请自行调试

**Comment by o-skyworth** [comment]
都是下午最近clone的，昨天clone的也是一样，不过这个问题不大
